### PR TITLE
Enable IP TTL mangle option.

### PR DESCRIPTION
**Pull request by ioctl-user**
This option is very useful with conjunction of iptables to hide tethering from the mobile operator.

### CODE REVIEW

**Comment by ShevT** [comment]
This has been [present](https://github.com/crdroidandroid/android_kernel_oneplus_sm8150/commit/56be01f5277a38bca372cab2b6a067925f954915) for a long time.

**Comment by ioctl-user** [comment]
> This has been [present](https://github.com/crdroidandroid/android_kernel_oneplus_sm8150/commit/56be01f5277a38bca372cab2b6a067925f954915) for a long time.

My pull request to the android_kernel_oneplus_sm8250 repo, while your link is to the android_kernel_oneplus_sm8150 repo. It's not the same.

**Comment by ioctl-user** [comment]
Please see updated pool request: https://github.com/crdroidandroid/android_kernel_oneplus_sm8250/pull/5 .

**Comment by ShevT** [comment]
> > This has been [present](https://github.com/crdroidandroid/android_kernel_oneplus_sm8150/commit/56be01f5277a38bca372cab2b6a067925f954915) for a long time.
> 
> My pull request to the android_kernel_oneplus_sm8250 repo, while your link is to the android_kernel_oneplus_sm8150 repo. It's not the same.

Oooh. Sorry.
In any case, this is not a complete commit.

**Comment by ioctl-user** [comment]
> Oooh. Sorry. In any case, this is not a complete commit.

Yes. Please see the following one: https://github.com/crdroidandroid/android_kernel_oneplus_sm8250/pull/5

**Pull request closed without merging**
